---
language: node_js

node_js: 12

branches:
  only:
  - hexo

before_install:
  - npm install -g hexo --force
  - npm install -g hexo-cli --force
  - npm install hexo-deployer-git --save

before_script:
  - git config user.name "jamesxwang"
  - git config user.email "xuwang2@student.unimelb.edu.au"
  - sed -i'' "s~https://github.com/jamesxwang/jamesxwang.github.io.git~https://${GITHUB_ACCESS_TOKEN}@github.com/jamesxwang/jamesxwang.github.io.git~" _config.yml

install:
  - npm install

cache:
  directories:
    - node_modules

script:
  - hexo clean
  - hexo g

after_success:
  - hexo deploy